packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - sharp
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - prisma
