import type { Job, Message, StatsResponse, MetricsResponse } from "../../web/lib/types";

// Mock data for development
export const mockJobs: Job[] = [
	{
		id: "job_1",
		definitionNL: "Send daily report emails to subscribers",
		status: "ACTIVE",
		nextRunAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
		contextEntries: 5,
		totalTokens: 1250,
		inputTokens: 800,
		outputTokens: 400,
		reasoningTokens: 50,
		createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
	},
	{
		id: "job_2",
		definitionNL: "Process webhook notifications from payment provider",
		status: "ACTIVE",
		nextRunAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
		contextEntries: 12,
		totalTokens: 890,
		inputTokens: 600,
		outputTokens: 250,
		reasoningTokens: 40,
		createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
	},
	{
		id: "job_3",
		definitionNL: "Generate weekly analytics summary",
		status: "PAUSED",
		nextRunAt: null,
		contextEntries: 3,
		totalTokens: 2100,
		inputTokens: 1400,
		outputTokens: 600,
		reasoningTokens: 100,
		createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
	},
	{
		id: "job_4",
		definitionNL: "Backup database to cloud storage",
		status: "ACTIVE",
		nextRunAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
		contextEntries: 1,
		totalTokens: 450,
		inputTokens: 300,
		outputTokens: 120,
		reasoningTokens: 30,
		createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
	},
	{
		id: "job_5",
		definitionNL: "Monitor API health and send alerts",
		status: "ARCHIVED",
		nextRunAt: null,
		contextEntries: 8,
		totalTokens: 675,
		inputTokens: 450,
		outputTokens: 180,
		reasoningTokens: 45,
		createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
	},
];

export const mockMessages: Message[] = [
	{
		id: "msg_1",
		role: "system",
		content: "Job 'Send daily reports' executed successfully. Processed 245 email addresses.",
		jobId: "job_1",
		createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
	},
	{
		id: "msg_2",
		role: "tool",
		content: "API endpoint /webhooks/payment responded with 200 OK. Processed payment confirmation for order #12345.",
		jobId: "job_2",
		createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
	},
	{
		id: "msg_3",
		role: "user",
		content: "Updated context variable 'max_retries' from 3 to 5 for better reliability.",
		jobId: "job_1",
		createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
	},
	{
		id: "msg_4",
		role: "system",
		content: "Job 'Monitor API health' detected elevated response times. Alert sent to #ops-alerts.",
		jobId: "job_5",
		createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
	},
	{
		id: "msg_5",
		role: "tool",
		content: "Database backup completed successfully. 2.3GB uploaded to cloud storage.",
		jobId: "job_4",
		createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
	},
];

export const mockStats: StatsResponse = {
	totalJobs: 12,
	messagesProcessedToday: 847,
	contextUpdatesLast24h: 23,
};

export const mockMetrics: MetricsResponse = {
	tokenUsage: [
		{ date: "Jan 1", input: 1200, output: 800, reasoning: 400 },
		{ date: "Jan 2", input: 1500, output: 950, reasoning: 520 },
		{ date: "Jan 3", input: 1100, output: 720, reasoning: 380 },
		{ date: "Jan 4", input: 1800, output: 1200, reasoning: 650 },
		{ date: "Jan 5", input: 1400, output: 900, reasoning: 480 },
		{ date: "Jan 6", input: 1600, output: 1050, reasoning: 580 },
		{ date: "Jan 7", input: 1300, output: 850, reasoning: 450 },
	],
	processingTime: [
		{ date: "Jan 1", avgTime: 2.3, maxTime: 8.1 },
		{ date: "Jan 2", avgTime: 1.8, maxTime: 6.4 },
		{ date: "Jan 3", avgTime: 2.1, maxTime: 7.2 },
		{ date: "Jan 4", avgTime: 2.7, maxTime: 9.3 },
		{ date: "Jan 5", avgTime: 2.0, maxTime: 6.8 },
		{ date: "Jan 6", avgTime: 2.4, maxTime: 8.5 },
		{ date: "Jan 7", avgTime: 1.9, maxTime: 6.1 },
	],
	contextSize: [
		{ date: "Jan 1", avgSize: 4.2, maxSize: 12.8 },
		{ date: "Jan 2", avgSize: 3.8, maxSize: 11.4 },
		{ date: "Jan 3", avgSize: 4.5, maxSize: 13.2 },
		{ date: "Jan 4", avgSize: 5.1, maxSize: 15.6 },
		{ date: "Jan 5", avgSize: 4.0, maxSize: 12.1 },
		{ date: "Jan 6", avgSize: 4.7, maxSize: 14.3 },
		{ date: "Jan 7", avgSize: 3.9, maxSize: 11.8 },
	],
};
