/* eslint-disable eslint-comments/no-unlimited-disable */

/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as LoginRouteImport } from './routes/~login'
import { Route as DashboardRouteRouteImport } from './routes/~dashboard/~route'
import { Route as IndexRouteImport } from './routes/~index'
import { Route as DashboardIndexRouteImport } from './routes/~dashboard/~index'
import { Route as DashboardJobsCreateRouteImport } from './routes/~dashboard/~jobs/~create'
import { Route as DashboardJobsJobIdRouteImport } from './routes/~dashboard/~jobs/~$jobId'
import { Route as DashboardApiKeysCreateRouteImport } from './routes/~dashboard/~api-keys/~create'
import { Route as DashboardApiKeysApiKeyIdRouteImport } from './routes/~dashboard/~api-keys/~$apiKeyId'
import { Route as DashboardJobsIndexRouteImport } from './routes/~dashboard/~jobs/~index'
import { Route as DashboardApiKeysIndexRouteImport } from './routes/~dashboard/~api-keys/~index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsCreateRoute = DashboardJobsCreateRouteImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsJobIdRoute = DashboardJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApiKeysCreateRoute = DashboardApiKeysCreateRouteImport.update({
  id: '/api-keys/create',
  path: '/api-keys/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApiKeysApiKeyIdRoute =
  DashboardApiKeysApiKeyIdRouteImport.update({
    id: '/api-keys/$apiKeyId',
    path: '/api-keys/$apiKeyId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApiKeysIndexRoute = DashboardApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/api-keys': typeof DashboardApiKeysIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/api-keys/$apiKeyId': typeof DashboardApiKeysApiKeyIdRoute
  '/dashboard/api-keys/create': typeof DashboardApiKeysCreateRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/jobs/create': typeof DashboardJobsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/api-keys': typeof DashboardApiKeysIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/api-keys/$apiKeyId': typeof DashboardApiKeysApiKeyIdRoute
  '/dashboard/api-keys/create': typeof DashboardApiKeysCreateRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/jobs/create': typeof DashboardJobsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/api-keys/': typeof DashboardApiKeysIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/api-keys/$apiKeyId': typeof DashboardApiKeysApiKeyIdRoute
  '/dashboard/api-keys/create': typeof DashboardApiKeysCreateRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/jobs/create': typeof DashboardJobsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/api-keys'
    | '/dashboard/jobs'
    | '/dashboard/api-keys/$apiKeyId'
    | '/dashboard/api-keys/create'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/jobs/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/api-keys'
    | '/dashboard/jobs'
    | '/dashboard/api-keys/$apiKeyId'
    | '/dashboard/api-keys/create'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/jobs/create'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/api-keys/'
    | '/dashboard/jobs/'
    | '/dashboard/api-keys/$apiKeyId'
    | '/dashboard/api-keys/create'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/jobs/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/create': {
      id: '/dashboard/jobs/create'
      path: '/jobs/create'
      fullPath: '/dashboard/jobs/create'
      preLoaderRoute: typeof DashboardJobsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/$jobId': {
      id: '/dashboard/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/dashboard/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/api-keys/create': {
      id: '/dashboard/api-keys/create'
      path: '/api-keys/create'
      fullPath: '/dashboard/api-keys/create'
      preLoaderRoute: typeof DashboardApiKeysCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/api-keys/$apiKeyId': {
      id: '/dashboard/api-keys/$apiKeyId'
      path: '/api-keys/$apiKeyId'
      fullPath: '/dashboard/api-keys/$apiKeyId'
      preLoaderRoute: typeof DashboardApiKeysApiKeyIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/api-keys/': {
      id: '/dashboard/api-keys/'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardApiKeysIndexRoute: typeof DashboardApiKeysIndexRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardApiKeysApiKeyIdRoute: typeof DashboardApiKeysApiKeyIdRoute
  DashboardApiKeysCreateRoute: typeof DashboardApiKeysCreateRoute
  DashboardJobsJobIdRoute: typeof DashboardJobsJobIdRoute
  DashboardJobsCreateRoute: typeof DashboardJobsCreateRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApiKeysIndexRoute: DashboardApiKeysIndexRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardApiKeysApiKeyIdRoute: DashboardApiKeysApiKeyIdRoute,
  DashboardApiKeysCreateRoute: DashboardApiKeysCreateRoute,
  DashboardJobsJobIdRoute: DashboardJobsJobIdRoute,
  DashboardJobsCreateRoute: DashboardJobsCreateRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
