/* eslint-disable eslint-comments/no-unlimited-disable */

/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as LoginRouteImport } from './routes/~login'
import { Route as DashboardRouteRouteImport } from './routes/~dashboard/~route'
import { Route as IndexRouteImport } from './routes/~index'
import { Route as DashboardIndexRouteImport } from './routes/~dashboard/~index'
import { Route as DashboardJobsCreateRouteImport } from './routes/~dashboard/~jobs/~create'
import { Route as DashboardJobsJobIdRouteRouteImport } from './routes/~dashboard/~jobs/~$jobId/~route'
import { Route as DashboardApiKeysCreateRouteImport } from './routes/~dashboard/~api-keys/~create'
import { Route as DashboardJobsIndexRouteImport } from './routes/~dashboard/~jobs/~index'
import { Route as DashboardEndpointUsageIndexRouteImport } from './routes/~dashboard/~endpoint-usage/~index'
import { Route as DashboardApiKeysIndexRouteImport } from './routes/~dashboard/~api-keys/~index'
import { Route as DashboardJobsJobIdIndexRouteImport } from './routes/~dashboard/~jobs/~$jobId/~index'
import { Route as DashboardJobsJobIdMessagesCreateRouteImport } from './routes/~dashboard/~jobs/~$jobId/~messages/~create'
import { Route as DashboardJobsJobIdMessagesMessagesIdRouteImport } from './routes/~dashboard/~jobs/~$jobId/~messages/~$messagesId'
import { Route as DashboardJobsJobIdEndpointsCreateRouteImport } from './routes/~dashboard/~jobs/~$jobId/~endpoints/~create'
import { Route as DashboardJobsJobIdEndpointsEndpointIdRouteImport } from './routes/~dashboard/~jobs/~$jobId/~endpoints/~$endpointId'
import { Route as DashboardJobsJobIdMessagesIndexRouteImport } from './routes/~dashboard/~jobs/~$jobId/~messages/~index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsCreateRoute = DashboardJobsCreateRouteImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsJobIdRouteRoute = DashboardJobsJobIdRouteRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApiKeysCreateRoute = DashboardApiKeysCreateRouteImport.update({
  id: '/api-keys/create',
  path: '/api-keys/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEndpointUsageIndexRoute =
  DashboardEndpointUsageIndexRouteImport.update({
    id: '/endpoint-usage/',
    path: '/endpoint-usage/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApiKeysIndexRoute = DashboardApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsJobIdIndexRoute = DashboardJobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardJobsJobIdRouteRoute,
} as any)
const DashboardJobsJobIdMessagesCreateRoute =
  DashboardJobsJobIdMessagesCreateRouteImport.update({
    id: '/messages/create',
    path: '/messages/create',
    getParentRoute: () => DashboardJobsJobIdRouteRoute,
  } as any)
const DashboardJobsJobIdMessagesMessagesIdRoute =
  DashboardJobsJobIdMessagesMessagesIdRouteImport.update({
    id: '/messages/$messagesId',
    path: '/messages/$messagesId',
    getParentRoute: () => DashboardJobsJobIdRouteRoute,
  } as any)
const DashboardJobsJobIdEndpointsCreateRoute =
  DashboardJobsJobIdEndpointsCreateRouteImport.update({
    id: '/endpoints/create',
    path: '/endpoints/create',
    getParentRoute: () => DashboardJobsJobIdRouteRoute,
  } as any)
const DashboardJobsJobIdEndpointsEndpointIdRoute =
  DashboardJobsJobIdEndpointsEndpointIdRouteImport.update({
    id: '/endpoints/$endpointId',
    path: '/endpoints/$endpointId',
    getParentRoute: () => DashboardJobsJobIdRouteRoute,
  } as any)
const DashboardJobsJobIdMessagesIndexRoute =
  DashboardJobsJobIdMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => DashboardJobsJobIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/api-keys': typeof DashboardApiKeysIndexRoute
  '/dashboard/endpoint-usage': typeof DashboardEndpointUsageIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/api-keys/create': typeof DashboardApiKeysCreateRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRouteRouteWithChildren
  '/dashboard/jobs/create': typeof DashboardJobsCreateRoute
  '/dashboard/jobs/$jobId/': typeof DashboardJobsJobIdIndexRoute
  '/dashboard/jobs/$jobId/messages': typeof DashboardJobsJobIdMessagesIndexRoute
  '/dashboard/jobs/$jobId/endpoints/$endpointId': typeof DashboardJobsJobIdEndpointsEndpointIdRoute
  '/dashboard/jobs/$jobId/endpoints/create': typeof DashboardJobsJobIdEndpointsCreateRoute
  '/dashboard/jobs/$jobId/messages/$messagesId': typeof DashboardJobsJobIdMessagesMessagesIdRoute
  '/dashboard/jobs/$jobId/messages/create': typeof DashboardJobsJobIdMessagesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/api-keys': typeof DashboardApiKeysIndexRoute
  '/dashboard/endpoint-usage': typeof DashboardEndpointUsageIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/api-keys/create': typeof DashboardApiKeysCreateRoute
  '/dashboard/jobs/create': typeof DashboardJobsCreateRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdIndexRoute
  '/dashboard/jobs/$jobId/messages': typeof DashboardJobsJobIdMessagesIndexRoute
  '/dashboard/jobs/$jobId/endpoints/$endpointId': typeof DashboardJobsJobIdEndpointsEndpointIdRoute
  '/dashboard/jobs/$jobId/endpoints/create': typeof DashboardJobsJobIdEndpointsCreateRoute
  '/dashboard/jobs/$jobId/messages/$messagesId': typeof DashboardJobsJobIdMessagesMessagesIdRoute
  '/dashboard/jobs/$jobId/messages/create': typeof DashboardJobsJobIdMessagesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/api-keys/': typeof DashboardApiKeysIndexRoute
  '/dashboard/endpoint-usage/': typeof DashboardEndpointUsageIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/api-keys/create': typeof DashboardApiKeysCreateRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRouteRouteWithChildren
  '/dashboard/jobs/create': typeof DashboardJobsCreateRoute
  '/dashboard/jobs/$jobId/': typeof DashboardJobsJobIdIndexRoute
  '/dashboard/jobs/$jobId/messages/': typeof DashboardJobsJobIdMessagesIndexRoute
  '/dashboard/jobs/$jobId/endpoints/$endpointId': typeof DashboardJobsJobIdEndpointsEndpointIdRoute
  '/dashboard/jobs/$jobId/endpoints/create': typeof DashboardJobsJobIdEndpointsCreateRoute
  '/dashboard/jobs/$jobId/messages/$messagesId': typeof DashboardJobsJobIdMessagesMessagesIdRoute
  '/dashboard/jobs/$jobId/messages/create': typeof DashboardJobsJobIdMessagesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/api-keys'
    | '/dashboard/endpoint-usage'
    | '/dashboard/jobs'
    | '/dashboard/api-keys/create'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/jobs/create'
    | '/dashboard/jobs/$jobId/'
    | '/dashboard/jobs/$jobId/messages'
    | '/dashboard/jobs/$jobId/endpoints/$endpointId'
    | '/dashboard/jobs/$jobId/endpoints/create'
    | '/dashboard/jobs/$jobId/messages/$messagesId'
    | '/dashboard/jobs/$jobId/messages/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/api-keys'
    | '/dashboard/endpoint-usage'
    | '/dashboard/jobs'
    | '/dashboard/api-keys/create'
    | '/dashboard/jobs/create'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/jobs/$jobId/messages'
    | '/dashboard/jobs/$jobId/endpoints/$endpointId'
    | '/dashboard/jobs/$jobId/endpoints/create'
    | '/dashboard/jobs/$jobId/messages/$messagesId'
    | '/dashboard/jobs/$jobId/messages/create'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/api-keys/'
    | '/dashboard/endpoint-usage/'
    | '/dashboard/jobs/'
    | '/dashboard/api-keys/create'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/jobs/create'
    | '/dashboard/jobs/$jobId/'
    | '/dashboard/jobs/$jobId/messages/'
    | '/dashboard/jobs/$jobId/endpoints/$endpointId'
    | '/dashboard/jobs/$jobId/endpoints/create'
    | '/dashboard/jobs/$jobId/messages/$messagesId'
    | '/dashboard/jobs/$jobId/messages/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/create': {
      id: '/dashboard/jobs/create'
      path: '/jobs/create'
      fullPath: '/dashboard/jobs/create'
      preLoaderRoute: typeof DashboardJobsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/$jobId': {
      id: '/dashboard/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/dashboard/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/api-keys/create': {
      id: '/dashboard/api-keys/create'
      path: '/api-keys/create'
      fullPath: '/dashboard/api-keys/create'
      preLoaderRoute: typeof DashboardApiKeysCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/endpoint-usage/': {
      id: '/dashboard/endpoint-usage/'
      path: '/endpoint-usage'
      fullPath: '/dashboard/endpoint-usage'
      preLoaderRoute: typeof DashboardEndpointUsageIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/api-keys/': {
      id: '/dashboard/api-keys/'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/$jobId/': {
      id: '/dashboard/jobs/$jobId/'
      path: '/'
      fullPath: '/dashboard/jobs/$jobId/'
      preLoaderRoute: typeof DashboardJobsJobIdIndexRouteImport
      parentRoute: typeof DashboardJobsJobIdRouteRoute
    }
    '/dashboard/jobs/$jobId/messages/create': {
      id: '/dashboard/jobs/$jobId/messages/create'
      path: '/messages/create'
      fullPath: '/dashboard/jobs/$jobId/messages/create'
      preLoaderRoute: typeof DashboardJobsJobIdMessagesCreateRouteImport
      parentRoute: typeof DashboardJobsJobIdRouteRoute
    }
    '/dashboard/jobs/$jobId/messages/$messagesId': {
      id: '/dashboard/jobs/$jobId/messages/$messagesId'
      path: '/messages/$messagesId'
      fullPath: '/dashboard/jobs/$jobId/messages/$messagesId'
      preLoaderRoute: typeof DashboardJobsJobIdMessagesMessagesIdRouteImport
      parentRoute: typeof DashboardJobsJobIdRouteRoute
    }
    '/dashboard/jobs/$jobId/endpoints/create': {
      id: '/dashboard/jobs/$jobId/endpoints/create'
      path: '/endpoints/create'
      fullPath: '/dashboard/jobs/$jobId/endpoints/create'
      preLoaderRoute: typeof DashboardJobsJobIdEndpointsCreateRouteImport
      parentRoute: typeof DashboardJobsJobIdRouteRoute
    }
    '/dashboard/jobs/$jobId/endpoints/$endpointId': {
      id: '/dashboard/jobs/$jobId/endpoints/$endpointId'
      path: '/endpoints/$endpointId'
      fullPath: '/dashboard/jobs/$jobId/endpoints/$endpointId'
      preLoaderRoute: typeof DashboardJobsJobIdEndpointsEndpointIdRouteImport
      parentRoute: typeof DashboardJobsJobIdRouteRoute
    }
    '/dashboard/jobs/$jobId/messages/': {
      id: '/dashboard/jobs/$jobId/messages/'
      path: '/messages'
      fullPath: '/dashboard/jobs/$jobId/messages'
      preLoaderRoute: typeof DashboardJobsJobIdMessagesIndexRouteImport
      parentRoute: typeof DashboardJobsJobIdRouteRoute
    }
  }
}

interface DashboardJobsJobIdRouteRouteChildren {
  DashboardJobsJobIdIndexRoute: typeof DashboardJobsJobIdIndexRoute
  DashboardJobsJobIdMessagesIndexRoute: typeof DashboardJobsJobIdMessagesIndexRoute
  DashboardJobsJobIdEndpointsEndpointIdRoute: typeof DashboardJobsJobIdEndpointsEndpointIdRoute
  DashboardJobsJobIdEndpointsCreateRoute: typeof DashboardJobsJobIdEndpointsCreateRoute
  DashboardJobsJobIdMessagesMessagesIdRoute: typeof DashboardJobsJobIdMessagesMessagesIdRoute
  DashboardJobsJobIdMessagesCreateRoute: typeof DashboardJobsJobIdMessagesCreateRoute
}

const DashboardJobsJobIdRouteRouteChildren: DashboardJobsJobIdRouteRouteChildren =
  {
    DashboardJobsJobIdIndexRoute: DashboardJobsJobIdIndexRoute,
    DashboardJobsJobIdMessagesIndexRoute: DashboardJobsJobIdMessagesIndexRoute,
    DashboardJobsJobIdEndpointsEndpointIdRoute:
      DashboardJobsJobIdEndpointsEndpointIdRoute,
    DashboardJobsJobIdEndpointsCreateRoute:
      DashboardJobsJobIdEndpointsCreateRoute,
    DashboardJobsJobIdMessagesMessagesIdRoute:
      DashboardJobsJobIdMessagesMessagesIdRoute,
    DashboardJobsJobIdMessagesCreateRoute:
      DashboardJobsJobIdMessagesCreateRoute,
  }

const DashboardJobsJobIdRouteRouteWithChildren =
  DashboardJobsJobIdRouteRoute._addFileChildren(
    DashboardJobsJobIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardApiKeysIndexRoute: typeof DashboardApiKeysIndexRoute
  DashboardEndpointUsageIndexRoute: typeof DashboardEndpointUsageIndexRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardApiKeysCreateRoute: typeof DashboardApiKeysCreateRoute
  DashboardJobsJobIdRouteRoute: typeof DashboardJobsJobIdRouteRouteWithChildren
  DashboardJobsCreateRoute: typeof DashboardJobsCreateRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApiKeysIndexRoute: DashboardApiKeysIndexRoute,
  DashboardEndpointUsageIndexRoute: DashboardEndpointUsageIndexRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardApiKeysCreateRoute: DashboardApiKeysCreateRoute,
  DashboardJobsJobIdRouteRoute: DashboardJobsJobIdRouteRouteWithChildren,
  DashboardJobsCreateRoute: DashboardJobsCreateRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
