version: "3"

services:
  web:
    container_name: web
    networks:
      - cronicorn
    build:
      context: ../
      dockerfile: docker/Dockerfile.web
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cronicorn
    volumes:
      - "../files/crondbvolume:/var/lib/postgresql/data"
  api:
    container_name: api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    networks:
      - cronicorn
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_URL: ${AUTH_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
networks:
  cronicorn:
    driver: bridge
