FROM node:20-alpine AS base
WORKDIR /app
RUN corepack enable
COPY . .
RUN pnpm i --frozen-lockfile

FROM base AS builder
WORKDIR /app
RUN pnpm --filter @tasks-app/web build

FROM nginx:alpine
ENV NODE_ENV=production
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf