name: 📦 Dependency consistency

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sync-deps:
    name: Dependency Consistency Check
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Check out your code
      - uses: actions/checkout@v4

      # 2️⃣ Install pnpm (optional, but recommended for pnpm workspaces)
      - uses: pnpm/action-setup@v3
        with:
          version: 10.7.0

      # 3️⃣ Install all dependencies
      - run: pnpm install

      # 4️⃣ Run Syncpack’s linter to catch any version mismatches
      - name: Check for version mismatches
        run: pnpm run sync:check
